export const CLOCK_STYLES = {
  default: {
    fontSize: 200,
    color: "#fff",
    fontWeight: "900",
    hourDigit: {},
    minuteDigit: {},
    colon: {},
    date: {},
    showSeconds: false,
    showDate: false,
    ampm: { fontSize: 20, color: "#fff", marginLeft: 10 },
  },
  defaultBackup: {
    fontSize: 80,
    color: "#fff",
    fontWeight: "bold",
    hourDigit: {},
    minuteDigit: {},
    secondDigit: {},
    colon: {},
    ampm: { fontSize: 30, color: "#fff" },
    date: { fontSize: 30, color: "#fff" },
    showSeconds: true,
    showDate: true,
  },
  sleek: {
    fontSize: 200,
    color: "#fff",
    fontWeight: "100",
    hourDigit: {},
    minuteDigit: {},
    colon: {},
    date: {},
    showSeconds: false,
    showDate: false,
    ampm: { fontSize: 20, color: "#fff", marginLeft: 10 },
  },
  hourMinbold: {
    fontSize: 200,
    color: "#fff",
    fontWeight: "900",
    hourDigit: {},
    minuteDigit: {},
    colon: {},
    date: {},
    showSeconds: false,
    showDate: false,
    ampm: { fontSize: 20, color: "#fff", marginLeft: 10 },
  },
  retroDigital: {
    fontSize: 80,
    color: "#0ff",
    fontFamily: "monospace", // or a custom font if you load one
    hourDigit: {},
    minuteDigit: {},
    secondDigit: {},
    colon: {},
    ampm: { fontSize: 30, color: "#0ff" },
    date: { fontSize: 30, color: "#0ff" },
    showSeconds: true,
    showDate: true,
  },
  verticalClock: {
    fontSize: 100,
    color: "#fff",
    fontWeight: "bold",
    vertical: true,
    hourText: { marginBottom: 10 },
    minuteText: {},
    showSeconds: false,
    showDate: false,
    showAMPM: false,
  },


  verticalClock: {
    fontSize: 80,
    color: "#fff",
    fontWeight: "bold",
    vertical: true,
    hourText: { marginBottom: 10 },
    minuteText: {},
    showSeconds: false,
    showDate: false,
    showAMPM: false,
  },

  verticalIosGreen: {
    fontSize: 160,
    color: "#AED2FE",
    fontWeight: "900",
    hourText: {
      marginBottom: 0,
      textAlign: "center",
    },
    minuteText: {
      marginTop: 0,
      textAlign: "center",
    },
    showSeconds: false,
    showAMPM: false,
    showDate: true,

    date: {
      fontSize: 24,
      color: "#32D74B",
    },
  },
  iosGreenExact: {
    exactIosGreen: true,
    color: "#AED2FE",
    fontSize: 160,
    fontWeight: "900",
    showSeconds: false,
    showDate: false,
    showAMPM: false,
  },

  
};
